#!/bin/sh

LOL_DIR="/Users/jz/learning-machine"

tmux new-session -d -s lol -c "$LOL_DIR/api"
tmux rename-window lol-app
tmux new-window -c $LOL_DIR

tmux select-window -t lol:lol-app

tmux split-window -v -c "$LOL_DIR/ui"
tmux split-window -h -t lol:lol-app.1 -c "$LOL_DIR/server"

# server (relies on api)
tmux select-pane -t lol:lol-app.2
# todo: stop using unreliable sleep when you figure out how to use the wait-for signals for persistent processes
#tmux send-keys "yarn; tmux wait-for api-started; yarn start" Enter
tmux send-keys "yarn; sleep 5" Enter
tmux send-keys "yarn start" Enter

# api
tmux select-pane -t lol:lol-app.1
# todo: this wait-for signal never gets sent because the `start` job never ends
tmux send-keys "yarn; yarn start; tmux wait-for -S api-started" Enter

# ui
tmux select-pane -t lol:lol-app.3
tmux send-keys "lsof -i :3000 | grep node | awk '{print \$2}' | xargs kill; yarn" Enter
tmux send-keys "yarn start" Enter


# update and run api
# update and run server
# update and run ui
# attach the session

tmux attach-session -t lol
